package uk.mhl.swapx.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF006C4D)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF87F8C9)
val light_onPrimaryContainer = Color(0xFF002115)
val light_secondary = Color(0xFF4C6358)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFCFE9DA)
val light_onSecondaryContainer = Color(0xFF092017)
val light_tertiary = Color(0xFF3E6374)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFC1E8FC)
val light_onTertiaryContainer = Color(0xFF001F2A)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFBFDF9)
val light_onBackground = Color(0xFF191C1A)
val light_surface = Color(0xFFFBFDF9)
val light_onSurface = Color(0xFF191C1A)
val light_surfaceVariant = Color(0xFFDBE5DE)
val light_onSurfaceVariant = Color(0xFF404944)
val light_outline = Color(0xFF707973)
val light_inverseOnSurface = Color(0xFFEFF1ED)
val light_inverseSurface = Color(0xFF2E312F)
val light_inversePrimary = Color(0xFF6ADBAE)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF006C4D)
val light_surfaceTintColor = Color(0xFF006C4D)

val dark_primary = Color(0xFF6ADBAE)
val dark_onPrimary = Color(0xFF003827)
val dark_primaryContainer = Color(0xFF00513A)
val dark_onPrimaryContainer = Color(0xFF87F8C9)
val dark_secondary = Color(0xFFB3CCBE)
val dark_onSecondary = Color(0xFF1F352B)
val dark_secondaryContainer = Color(0xFF354B41)
val dark_onSecondaryContainer = Color(0xFFCFE9DA)
val dark_tertiary = Color(0xFFA6CCDF)
val dark_onTertiary = Color(0xFF083544)
val dark_tertiaryContainer = Color(0xFF254B5B)
val dark_onTertiaryContainer = Color(0xFFC1E8FC)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF191C1A)
val dark_onBackground = Color(0xFFE1E3DF)
val dark_surface = Color(0xFF191C1A)
val dark_onSurface = Color(0xFFE1E3DF)
val dark_surfaceVariant = Color(0xFF404944)
val dark_onSurfaceVariant = Color(0xFFBFC9C2)
val dark_outline = Color(0xFF8A938D)
val dark_inverseOnSurface = Color(0xFF191C1A)
val dark_inverseSurface = Color(0xFFE1E3DF)
val dark_inversePrimary = Color(0xFF006C4D)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFF6ADBAE)
val dark_surfaceTintColor = Color(0xFF6ADBAE)

val seed = Color(0xFF136C4F)